sudo: false
language: python

matrix:
    include:
        - python: 2.7  # these are just to make travis's UI a bit prettier
          env: TOXENV=py27-trollius
        - python: 3.2
          env: TOXENV=py32-trollius
        - python: 3.3
          env: TOXENV=py33-trollius
        - python: 3.3
          env: TOXENV=py33-tulip
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: nightly
          env: TOXENV=py-nightly

        - python: pypy
          env: TOXENV=pypy-trollius
        - python: pypy3
          env: TOXENV=pypy3-trollius

        - python: 3.5
          env: TOXENV=packaging
        - python: 3.5
          env: TOXENV=docs
        - python: 3.5
          env: TOXENV=py3-pep8
        - python: 2.7
          env: TOXENV=py2-pep8

    allow_failures:
        - python: nightly
          env: TOXENV=py-nightly

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - x11-apps
    - xserver-xephyr
    - xvfb
    - graphviz # for docs

before_install:
  # Setup XvFB
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install tox python-coveralls

script:
  - tox


after_success:
  - coveralls

notifications:
  email: false


