language: python

# Install trollius for 2, 3.2, and pypy
# Install either trollius or tulip for 3.3
# Asyncio is in the standard library for 3.4+
matrix:
  include:
    - python: 2.7
      env: EVENTLOOP=trollius
    - python: 3.2
      env: EVENTLOOP=trollius
    - python: 3.3
      env: EVENTLOOP=trollius
    - python: 3.3
      env: EVENTLOOP=tulip
    - python: 3.4
      env: EVENTLOOP=asyncio
    - python: 3.5
      env: EVENTLOOP=asyncio
    - python: pypy
      env: EVENTLOOP=trollius
    - python: pypy3
      env: EVENTLOOP=trollius
    - python: nightly
      env: EVENTLOOP=asyncio
  allow_failures:
    - python: pypy3
    - python: nightly

script:
  - make ckpatch

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - x11-apps
      - xserver-xephyr
      - xvfb

before_install:
# Setup XvFB
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
# Installl requirements
  - pip install xcffib
  - pip install -r requirements-dev.txt
  - if [[ ${EVENTLOOP} == "trollius" ]]; then pip install trollius; fi
  - if [[ ${EVENTLOOP} == "tulip" ]]; then pip install asyncio; fi
# build pangocffi module
  - python -c 'import cffi, sys; sys.exit(cffi.__version_info__[0])' || python libqtile/ffi_build.py

after_success:
  - coveralls

notifications:
  email: false

sudo: false
