sudo: false
dist: trusty
language: python

matrix:
    include:
        - python: 2.7  # these are just to make travis's UI a bit prettier
          env: TOXENV=py27-trollius
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: nightly
          env: TOXENV=py-nightly

        - python: pypy
          env: TOXENV=pypy-trollius
        - python: pypy3
          env: TOXENV=pypy3

        - python: 3.6
          env: TOXENV=packaging
        - python: 3.6
          env: TOXENV=docs
        - python: 3.6
          env: TOXENV=pep8
        - python: 2.7
          env: TOXENV=pep8

    allow_failures:
        - python: nightly
          env: TOXENV=py-nightly
        - python: pypy3
          env: TOXENV=pypy3

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - x11-apps
    - xserver-xephyr
    - xvfb
    - graphviz # for docs

install:
  - pip install tox
  - if [[ $TOXENV == py* ]]; then pip install coveralls; fi

script:
  - travis_wait 30 script.sh
  - detox

notifications:
  email: false

after_success:
  - if [[ $TOXENV == py* ]]; then coveralls; fi
