language: python

python:
  - 2.6
  - 2.7

script:
  make lint
  nosetests

before_install:
# Environment setup
  - sudo apt-get update -qq
  - sudo apt-get install xserver-xephyr x11-apps
  - sudo pip install flake8
# Setup XvFB
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
# Installation environment variables
  - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
  - export CONFIG_OPTS="--prefix=$VIRT_ROOT --includedir=/usr/include  --libdir=/usr/lib --datarootdir=/usr/share"
# Ubuntu 12.04 needs updated xcb-proto (>=1.7.1) to install latest xpyb
# See https://github.com/travis-ci/travis-ci/issues/2046
  - wget http://xcb.freedesktop.org/dist/xcb-proto-1.10.tar.bz2
  - tar xjf xcb-proto-1.10.tar.bz2
  - pushd xcb-proto-1.10
  - ./configure $CONFIG_OPTS
  - make -j3
  - sudo make install
  - popd
# Install xpyb (xcb module)
  - wget http://xcb.freedesktop.org/dist/xpyb-1.3.1.tar.bz2
  - tar xjf xpyb-1.3.1.tar.bz2
  - pushd xpyb-1.3.1
  - ./configure $CONFIG_OPTS
  - make -j3
  - sudo make install
  - popd
# Install pygobject (gobject module)
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
  - tar xjf pygobject-2.28.6.tar.bz2
  - pushd pygobject-2.28.6
  - ./configure $CONFIG_OPTS --disable-introspection
  - make -j3
  - sudo make install
  - popd
# Install pycairo (cairo module)
  - wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
  - tar xjf py2cairo-1.10.0.tar.bz2
  - pushd py2cairo-1.10.0
# Need to use autotools for xpyb support?
  - touch ChangeLog && autoreconf -fi
  - ./configure $CONFIG_OPTS
  - make -j3
  - sudo make install
  - popd
# Install pygtk (pango and pangocairo modules)
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xjf pygtk-2.24.0.tar.bz2
  - pushd pygtk-2.24.0
  - ./configure $CONFIG_OPTS
  - make -j3
  - sudo make install
  - popd

notifications:
  - email: false
